import { useEffect, useState } from 'react'
import { api, formatMoney } from '../api.js'
export default function ApprovalButtons({ scenarioId, wallet, recommendation, onRecorded }) {
  const eligible = recommendation?.action === 'propose_bounded_simulated_hold' && Number(recommendation.proposed_simulated_hold_bdt) > 0
  const [decision, setDecision] = useState('approve'); const [amount, setAmount] = useState(recommendation?.proposed_simulated_hold_bdt || '0.00'); const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [recorded, setRecorded] = useState(null); const [outcome, setOutcome] = useState(null)
  useEffect(() => { setDecision(eligible ? 'approve' : 'reject'); setAmount(recommendation?.proposed_simulated_hold_bdt || '0.00'); setRecorded(null); setOutcome(null); setError('') }, [scenarioId, wallet?.wallet_id, eligible, recommendation?.proposed_simulated_hold_bdt])
  const record = async () => { if (!wallet || !reason) { setError('Select a wallet and choose a reason code.'); return } setSaving(true); setError(''); try { const saved = await api('/api/decisions', { method: 'POST', body: JSON.stringify({ scenario_id: scenarioId, wallet_id: wallet.wallet_id, decision, proposed_amount_bdt: decision === 'reject' ? '0.00' : amount, reason, actor: 'demo_supervisor' }) }); setRecorded(saved); onRecorded?.() } catch (e) { setError(e.message) } finally { setSaving(false) } }
  const simulate = async () => { setSaving(true); try { setOutcome(await api(`/api/simulation/${recorded.decision_id}`, { method: 'POST' })); onRecorded?.() } catch (e) { setError(e.message) } finally { setSaving(false) } }
  return <section className="content-card approval-card"><h2>Decision</h2>{!wallet ? <div className="empty-state compact-empty">Select a wallet to review its proposed freeze.</div> : <><div className="decision-target"><span>Proposed freeze</span><b>{formatMoney(recommendation?.proposed_simulated_hold_bdt)}</b><small>Decided by: Demo supervisor</small></div>{!eligible && <div className="review-only-note">No freeze is proposed for this wallet under the current evidence. A rejection can still be recorded.</div>}{!recorded ? <><div className="decision-options">{['approve', 'modify', 'reject'].map((item) => <button key={item} className={`decision-option ${decision === item ? `chosen chosen-${item}` : ''}`} disabled={item !== 'reject' && !eligible} onClick={() => setDecision(item)}>{item === 'approve' ? 'Approve' : item === 'modify' ? 'Modify' : 'Reject'}</button>)}</div>{decision !== 'reject' && <label className="form-label">FREEZE AMOUNT<input type="number" min="0.01" max={Number(wallet.balance_bdt)} step="1" value={amount} onChange={(e) => setAmount(e.target.value)} /></label>}<label className="form-label">REASON CODE<select value={reason} onChange={(e) => setReason(e.target.value)}><option value="">Choose a reason</option><option value="high_risk_multi_hop">High risk, multi-hop movement</option><option value="rapid_forwarding">Rapid forwarding observed</option><option value="cashout_signal">Cash-out signal</option><option value="insufficient_evidence">Insufficient evidence</option><option value="customer_dispute">Customer dispute</option></select></label><div className="read-only-actor">Decided by: <b>Demo supervisor</b></div>{error && <div className="inline-error">{error}</div>}<button className="button button-primary full-button" disabled={saving} onClick={record}>{saving ? 'Submitting…' : 'Submit decision'} <span>→</span></button></> : <div className="recorded-box"><div className="recorded-check">✓</div><b>Decision submitted</b><span>Recorded in the synthetic audit trail. No live action was taken.</span>{!outcome ? <button className="button button-secondary full-button" disabled={saving} onClick={simulate}>{saving ? 'Calculating…' : 'Run simulated outcome'}</button> : <div className="outcome-box"><b>Scenario estimate</b><span>Suspicious funds preserved <strong>{formatMoney(outcome.estimated_tainted_preserved_bdt)}</strong></span><span>Legitimate value affected <strong>{formatMoney(outcome.estimated_legitimate_value_affected_bdt)}</strong></span></div>}</div>}</>}</section>
}
