import { useEffect, useMemo, useState } from 'react'
import { categoryOf, formatDate, formatMoney, shortCaseId } from '../api.js'
const patterns = ['All', 'Fan-out', 'Rapid movement', 'Mule', 'Slow mule', 'Likely legitimate']
export default function Cases({ incidents = [], onSelect }) {
  const [pattern, setPattern] = useState('All'), [query, setQuery] = useState(''), [status, setStatus] = useState('all'), [min, setMin] = useState(''), [max, setMax] = useState(''), [sort, setSort] = useState({ key: 'reported_amount', direction: 'desc' }), [page, setPage] = useState(0)
  useEffect(() => { const handle = (event) => { setPattern(event.detail || 'All'); setPage(0) }; window.addEventListener('flowfreeze:filter-pattern', handle); return () => window.removeEventListener('flowfreeze:filter-pattern', handle) }, [])
  const count = (name) => name === 'All' ? incidents.length : incidents.filter((item) => categoryOf(item.scenario_type) === name).length
  const filtered = useMemo(() => incidents.filter((item) => { const amount = Number(item.reported_amount || 0); return (pattern === 'All' || categoryOf(item.scenario_type) === pattern) && (!query || `${item.incident_id} ${item.scenario_id}`.toLowerCase().includes(query.toLowerCase())) && (status === 'all' || (item.status || 'new') === status) && (!min || amount >= Number(min)) && (!max || amount <= Number(max)) }).sort((a, b) => { const av = sort.key === 'category' ? categoryOf(a.scenario_type) : sort.key === 'status' ? a.status : Number(a[sort.key] || 0); const bv = sort.key === 'category' ? categoryOf(b.scenario_type) : sort.key === 'status' ? b.status : Number(b[sort.key] || 0); return (av > bv ? 1 : av < bv ? -1 : 0) * (sort.direction === 'asc' ? 1 : -1) }), [incidents, pattern, query, status, min, max, sort])
  const size = 12, pages = Math.max(1, Math.ceil(filtered.length / size)), visible = filtered.slice(page * size, (page + 1) * size)
  const sortBy = (key) => setSort((old) => ({ key, direction: old.key === key && old.direction === 'desc' ? 'asc' : 'desc' }))
  const header = (label, key) => <button className="sort-button" onClick={() => sortBy(key)}>{label} {sort.key === key ? (sort.direction === 'asc' ? '↑' : '↓') : '↕'}</button>
  return <><div className="page-heading heading-row"><div><h1>Cases</h1><p>{incidents.length} cases are under review.</p></div></div><div className="pattern-tabs" role="tablist">{patterns.map((item) => <button key={item} className={pattern === item ? 'active' : ''} onClick={() => { setPattern(item); setPage(0) }}>{item}<span>{count(item)}</span></button>)}</div><section className="content-card queue-card"><div className="queue-toolbar"><input className="incident-search" aria-label="Search by case ID" placeholder="Search case ID" value={query} onChange={(e) => { setQuery(e.target.value); setPage(0) }} /><select aria-label="Filter by status" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option><option value="new">New</option><option value="reviewed">Reviewed</option></select><input aria-label="Minimum amount" inputMode="numeric" placeholder="Min ৳" value={min} onChange={(e) => setMin(e.target.value)} /><input aria-label="Maximum amount" inputMode="numeric" placeholder="Max ৳" value={max} onChange={(e) => setMax(e.target.value)} /></div><div className="table-scroll"><table className="data-table queue-table"><thead><tr><th>{header('Case ID', 'incident_id')}</th><th>{header('Pattern', 'category')}</th><th>{header('Amount', 'reported_amount')}</th><th>{header('Reported', 'reported_at')}</th><th>{header('Status', 'status')}</th></tr></thead><tbody>{visible.map((item) => <tr key={item.incident_id} tabIndex="0" onClick={() => onSelect(item.scenario_id)} onKeyDown={(e) => e.key === 'Enter' && onSelect(item.scenario_id)}><td><b>{shortCaseId(item.incident_id)}</b></td><td><span className="pattern-tag">{categoryOf(item.scenario_type)}</span></td><td className="amount-cell">{formatMoney(item.reported_amount)}</td><td>{formatDate(item.reported_at)}</td><td><span className="status-pill">{item.status || 'new'}</span></td></tr>)}</tbody></table>{!visible.length && <div className="empty-state">No cases match these filters.</div>}</div><div className="table-foot"><span>Showing {filtered.length ? page * size + 1 : 0}–{Math.min((page + 1) * size, filtered.length)} of {filtered.length}</span><div className="pagination"><button disabled={!page} onClick={() => setPage((p) => p - 1)}>←</button><span>{page + 1} / {pages}</span><button disabled={page + 1 >= pages} onClick={() => setPage((p) => p + 1)}>→</button></div></div></section></>
}
