import { useEffect, useMemo, useState } from 'react'
import { api, categoryOf, formatDate, formatMoney, shortCaseId } from '../api.js'
import StatCard from '../components/StatCard.jsx'
export default function Dashboard({ incidents = [], totalCount, metrics, onSelect, loading }) {
  const [decisions, setDecisions] = useState([])
  useEffect(() => { api('/api/decisions?limit=5').then((data) => setDecisions(data.decisions || [])).catch(() => setDecisions([])) }, [metrics])
  const featured = incidents.find((item) => item.scenario_type === 'fanout_cashout') || incidents.find((item) => item.scenario_type === 'multi_hop') || incidents[0]
  const amount = useMemo(() => incidents.reduce((sum, item) => sum + Number(item.reported_amount || 0), 0), [incidents])
  const comparison = metrics?.end_to_end_evaluation?.results, baseline = comparison?.direct_recipient_only, network = comparison?.flowfreeze_network
  const ratio = Number(baseline?.estimated_tainted_value_preserved_bdt || 0) ? (Number(network?.estimated_tainted_value_preserved_bdt || 0) / Number(baseline.estimated_tainted_value_preserved_bdt)).toFixed(1) : '—'
  const counts = ['Fan-out', 'Rapid movement', 'Mule', 'Slow mule', 'Likely legitimate'].map((label) => ({ label, count: incidents.filter((item) => categoryOf(item.scenario_type) === label).length }))
  return <><div className="page-heading heading-row"><div><h1>Overview</h1><p>{totalCount || incidents.length} cases are under review.</p></div><button className="button button-primary" onClick={() => featured && onSelect(featured.scenario_id)}>Open featured case <span>→</span></button></div><div className="stats-grid"><StatCard label="Cases under review" value={totalCount || incidents.length} sub="Synthetic review queue" icon="◷" tone="green" /><StatCard label="Amount under review" value={formatMoney(amount)} sub="Reported transaction amounts" icon="৳" tone="blue" /><StatCard label="Decisions recorded" value={metrics?.audit?.decision_count ?? 0} sub="Approved, modified, or rejected" icon="✓" tone="violet" /><StatCard label="Funds preserved in simulations" value={Number(metrics?.simulations?.estimated_tainted_value_preserved_bdt || 0) ? formatMoney(metrics.simulations.estimated_tainted_value_preserved_bdt) : '—'} sub="Synthetic estimates only" icon="↗" tone="amber" /></div><section className="content-card comparison-card"><h2>Why tracing matters</h2><p className="comparison-headline">About {ratio}× more suspicious funds preserved</p><div className="comparison-values"><div><span>Direct recipient only</span><b>{formatMoney(baseline?.estimated_tainted_value_preserved_bdt)}</b><small>Legitimate funds affected: {formatMoney(baseline?.estimated_legitimate_value_affected_bdt)}</small></div><div className="comparison-highlight"><span>FlowFreeze network</span><b>{formatMoney(network?.estimated_tainted_value_preserved_bdt)}</b><small>Legitimate funds affected: {formatMoney(network?.estimated_legitimate_value_affected_bdt)}</small></div></div></section><div className="overview-grid"><section className="content-card"><div className="section-head"><h2>Pattern breakdown</h2></div><div className="pattern-breakdown">{counts.map((item) => <button key={item.label} onClick={() => { window.dispatchEvent(new CustomEvent('flowfreeze:navigate', { detail: 'cases' })); window.setTimeout(() => window.dispatchEvent(new CustomEvent('flowfreeze:filter-pattern', { detail: item.label })), 0) }}><span>{item.label}</span><div><i style={{ width: `${Math.max(4, item.count / Math.max(1, incidents.length) * 100)}%` }} /></div><b>{item.count}</b></button>)}</div></section><section className="content-card"><div className="section-head"><h2>Recent decisions</h2><button className="text-action" onClick={() => window.dispatchEvent(new CustomEvent('flowfreeze:navigate', { detail: 'audit' }))}>Audit trail →</button></div>{loading ? <div className="empty-state">Loading summary…</div> : !decisions.length ? <div className="empty-state">No decisions yet.</div> : <div className="recent-list">{decisions.map((item) => <div key={item.decision_id}><span>{formatDate(item.created_at)}</span><b>{shortCaseId(item.scenario_id)}</b><em className={`decision-pill decision-${item.decision}`}>{item.decision}</em><strong>{formatMoney(item.proposed_amount_bdt)}</strong></div>)}</div>}</section></div></>
}
