import { useMemo, useState } from 'react'
import StatCard from '../components/StatCard.jsx'
import { formatMoney, maskWallet, relativeTime, shortCaseId } from '../api.js'
const label=(value='')=>value.replaceAll('_',' ')
const riskFor=(row)=>Number(row.risk_score ?? row.risk ?? 0)>=.7?'High':Number(row.risk_score ?? row.risk ?? 0)>=.4?'Medium':'Low'
export default function Dashboard({incidents,totalCount,metrics,onSelect,loading}){
 const [query,setQuery]=useState(''),[risk,setRisk]=useState('all'),[page,setPage]=useState(0);const size=10
 const filtered=useMemo(()=>incidents.filter(row=>{const term=query.trim().toLowerCase();return(!term||`${row.incident_id} ${row.scenario_id} ${row.scenario_type} ${row.incident_type} ${row.source_wallet}`.toLowerCase().includes(term))&&(risk==='all'||riskFor(row).toLowerCase()===risk)}),[incidents,query,risk])
 const visible=filtered.slice(page*size,(page+1)*size),pages=Math.max(1,Math.ceil(filtered.length/size));const featured=incidents.find(row=>/slow|chain/i.test(row.scenario_type||''))||incidents[0];const comparison=metrics?.end_to_end_evaluation?.results,baseline=comparison?.direct_recipient_only,network=comparison?.flowfreeze_network
 return <><div className="page-heading heading-row"><div><h1>Overview</h1><p>{totalCount||0} cases are ready for supervisor review.</p></div><button className="button button-primary" onClick={()=>featured&&onSelect(featured.scenario_id)}>Open featured case <span>→</span></button></div>
 <div className="stats-grid"><StatCard label="Waiting for decision" value={incidents.filter(x=>!x.status||x.status==='new').length||totalCount||'—'} sub="Cases in the review queue" icon="◷" tone="green"/><StatCard label="Amount proposed to freeze" value={formatMoney(metrics?.simulations?.estimated_tainted_value_preserved_bdt)} sub="Synthetic estimate" icon="৳" tone="blue"/><StatCard label="Oldest waiting" value={incidents[0]?relativeTime(incidents[0].reported_at).replace(' ago',''):'—'} sub="Since report time" icon="◴" tone="amber"/><StatCard label="Decided today" value={metrics?.audit?.decision_count??0} sub="Approved, modified, or rejected" icon="✓" tone="violet"/></div>
 <section className="content-card comparison-card"><div><h2>Why tracing matters</h2><p>Estimated suspicious funds preserved with and without downstream tracing.</p></div><div className="comparison-values"><div><span>Direct recipient only</span><b>{formatMoney(baseline?.estimated_tainted_value_preserved_bdt)}</b><small>Legitimate funds affected: {formatMoney(baseline?.estimated_legitimate_value_affected_bdt)}</small></div><div className="comparison-highlight"><span>With FlowFreeze tracing</span><b>{formatMoney(network?.estimated_tainted_value_preserved_bdt)}</b><small>Legitimate funds affected: {formatMoney(network?.estimated_legitimate_value_affected_bdt)}</small></div></div><button className="text-action" onClick={()=>window.dispatchEvent(new CustomEvent('flowfreeze:navigate',{detail:'evaluation'}))}>See full evaluation →</button></section>
 <section className="content-card incident-list-card"><div className="section-head"><div><h2>Cases waiting for decision <span className="count-badge">{totalCount}</span></h2></div><div className="list-tools"><input className="incident-search" aria-label="Search cases" value={query} onChange={e=>{setQuery(e.target.value);setPage(0)}} placeholder="Search cases"/><select aria-label="Filter by risk" value={risk} onChange={e=>{setRisk(e.target.value);setPage(0)}}><option value="all">All risk</option><option value="high">High risk</option><option value="medium">Medium risk</option><option value="low">Low risk</option></select></div></div>{loading?<div className="empty-state">Loading cases…</div>:<div className="table-scroll"><table className="data-table incident-table"><thead><tr><th>CASE ID</th><th>RISK</th><th>AMOUNT</th><th>WALLET</th><th>PROPOSED FREEZE</th><th>AGE</th><th>STATUS</th></tr></thead><tbody>{visible.map(item=><tr key={item.incident_id} onClick={()=>onSelect(item.scenario_id)} tabIndex="0" onKeyDown={e=>e.key==='Enter'&&onSelect(item.scenario_id)}><td><div className="incident-id">{shortCaseId(item.incident_id)}</div></td><td><span className={`risk-pill risk-${riskFor(item).toLowerCase()}`}>{riskFor(item)}</span></td><td className="amount-cell">{formatMoney(item.reported_amount)}</td><td title={item.source_wallet}>{maskWallet(item.source_wallet||item.wallet_id)}</td><td>{formatMoney(item.proposed_simulated_hold_bdt)}</td><td className="date-cell">{relativeTime(item.reported_at)}</td><td><span className="status-pill">{label(item.status||'waiting')}</span></td></tr>)}</tbody></table>{!visible.length&&<div className="empty-state">No cases match those filters. Clear the search or risk filter.</div>}</div>}<div className="table-foot"><span>Showing {filtered.length?page*size+1:0}–{Math.min((page+1)*size,filtered.length)} of {filtered.length} cases</span><div className="pagination"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>←</button><span>{page+1} / {pages}</span><button disabled={page+1>=pages} onClick={()=>setPage(p=>p+1)}>→</button></div></div></section>
 <div className="dashboard-bottom-grid"><section className="content-card quick-card"><h2>Recent decisions</h2><p>{metrics?.audit?.decision_count||0} decisions have been recorded in this demo session.</p><button className="text-action" onClick={()=>window.dispatchEvent(new CustomEvent('flowfreeze:navigate',{detail:'audit'}))}>Open audit trail →</button></section><section className="content-card mini-stat-card"><h2>Decision summary</h2><div className="mini-stat-row"><span>Approved</span><b>{metrics?.audit?.decision_counts?.approve??0}</b></div><div className="mini-stat-row"><span>Modified</span><b>{metrics?.audit?.decision_counts?.modify??0}</b></div><div className="mini-stat-row"><span>Rejected</span><b>{metrics?.audit?.decision_counts?.reject??0}</b></div></section></div></>
}
