"""Small, deterministic scenario library; all identities and values are synthetic."""

SCENARIOS = [
    {
        "scenario_id": "SCN-01-DIRECT",
        "scenario_type": "direct_fraud",
        "fraud": True,
        "incident_type": "suspected_fraud",
        "source": "W1",
        "wallets": {"VICTIM": ("individual", 100000), "W1": ("individual", 300)},
        "events": [(0, "VICTIM", "W1", 50000, "transfer")],
    },
    {
        "scenario_id": "SCN-02-FANOUT",
        "scenario_type": "fanout",
        "fraud": True,
        "incident_type": "suspected_fraud",
        "source": "W1",
        "wallets": {"VICTIM": ("individual", 100000), "W1": ("individual", 500), "W2": ("individual", 200), "W3": ("individual", 800), "W4": ("individual", 100)},
        "events": [(0, "VICTIM", "W1", 50000, "transfer"), (2, "W1", "W2", 24000, "transfer"), (3, "W1", "W3", 18000, "transfer"), (6, "W2", "W4", 12000, "transfer")],
    },
    {
        "scenario_id": "SCN-03-MULTIHOP",
        "scenario_type": "multi_hop",
        "fraud": True,
        "incident_type": "suspected_fraud",
        "source": "W1",
        "wallets": {"VICTIM": ("individual", 90000), "W1": ("individual", 250), "W2": ("individual", 500), "W3": ("individual", 200), "W4": ("individual", 100)},
        "events": [(0, "VICTIM", "W1", 42000, "transfer"), (2, "W1", "W2", 39000, "transfer"), (3, "W2", "W3", 36000, "transfer"), (6, "W3", "W4", 32000, "transfer")],
    },
    {
        "scenario_id": "SCN-04-MIXED",
        "scenario_type": "mixed_balance",
        "fraud": True,
        "incident_type": "suspected_fraud",
        "source": "W1",
        "wallets": {"VICTIM": ("individual", 70000), "W1": ("individual", 1000), "W2": ("merchant", 15000), "W3": ("individual", 6000), "W4": ("individual", 100)},
        "events": [(0, "VICTIM", "W1", 30000, "transfer"), (2, "W1", "W2", 12000, "transfer"), (3, "W2", "W3", 10000, "transfer"), (6, "W3", "W4", 5000, "transfer")],
    },
    {
        "scenario_id": "SCN-05-CASHOUT",
        "scenario_type": "rapid_cashout",
        "fraud": True,
        "incident_type": "suspected_fraud",
        "source": "W1",
        "wallets": {"VICTIM": ("individual", 60000), "W1": ("individual", 400), "AGENT1": ("agent", 300000), "CASH1": ("cash_destination", 0)},
        "events": [(0, "VICTIM", "W1", 25000, "transfer"), (2, "W1", "CASH1", 20000, "cashout")],
    },
    {
        "scenario_id": "SCN-06-FANOUT-CASHOUT",
        "scenario_type": "fanout_cashout",
        "fraud": True,
        "incident_type": "suspected_fraud",
        "source": "W1",
        "wallets": {"VICTIM": ("individual", 70000), "W1": ("individual", 300), "W2": ("individual", 500), "W3": ("individual", 1000), "W4": ("individual", 200), "AGENT1": ("agent", 300000), "CASH1": ("cash_destination", 0)},
        "events": [(0, "VICTIM", "W1", 50000, "transfer"), (2, "W1", "W2", 22000, "transfer"), (3, "W1", "CASH1", 15000, "cashout"), (3, "W2", "W3", 18000, "transfer"), (6, "W3", "W4", 9000, "transfer")],
    },
    {
        "scenario_id": "SCN-07-NEAR-MISS",
        "scenario_type": "false_positive",
        "fraud": False,
        "incident_type": "suspected_fraud",
        "source": "W1",
        "wallets": {"VICTIM": ("individual", 70000), "W1": ("merchant", 40000), "W2": ("merchant", 10000)},
        "events": [(0, "VICTIM", "W1", 28000, "transfer"), (2, "W1", "W2", 15000, "merchant_payment")],
    },
    {
        "scenario_id": "SCN-08-WRONG-RECIPIENT",
        "scenario_type": "wrong_recipient",
        "fraud": False,
        "incident_type": "wrong_recipient_dispute",
        "source": "W1",
        "wallets": {"VICTIM": ("individual", 40000), "W1": ("individual", 5000)},
        "events": [(0, "VICTIM", "W1", 12000, "transfer")],
    },
]
